### ISSUE TITLE
can not access "/dataset/gpmdb/GPM11210002594"

### ISSUE THREAD

**Issue by Ricardo-Ke** [BD2K-DDI/ddi-web-app#107]
When accessing the "/dataset/gpmdb/GPM11210002594" ,the page is completely empty and the console print the error:

[http://errors.angularjs.org/1.4.7/$parse/syntax?p0=%2F&p1=not%20a%20primary%20expression&p2=1&p3=%2Fi&p4=%2Fi](http://errors.angularjs.org/1.4.7/$parse/syntax?p0=%2F&p1=not%20a%20primary%20expression&p2=1&p3=%2Fi&p4=%2Fi)

The bug is due to meta_dataset_abstract's content including `{{i}}  {{/i}}` getting from the api`http://www.omicsdi.org/ws/dataset/get?acc=GPM11210002594&database=gpmdb`.Angular will regard them as normal expression to parse,but they are not rightful inside `""` punctuation.So we replace it with empty space in back-end by java.

Any questions about dasaset pages are welcome.

**Comment by Ricardo-Ke** [comment]
@ypriverol @mindcrusher11

**Comment by ypriverol** [comment]
@Ricardo-Ke Great to see this issue here. I told with @baimingze before that for some providers we will have html characters. This is the case for GPMDB ArrayExpress and PeptideAtlas. My question is:

Can we render this text using the HTML tags? then we don't need to care in the server side about it. In this particular example will be render {{i}} {{/i}} as <i> </i> is that possible. If not we can remove it.

**Comment by Ricardo-Ke** [comment]
It is best to remove it

**Comment by Ricardo-Ke** [comment]
Where should we place the text using the HTML tags?I've got a similar question:

when i access `http://localhost:8080/dataset/ega/phs000664.v1.p1`, the page went chaotic due to the \<a\> tag inside the dataset_abstract meta content,so which solution should we adopt?

**Comment by Ricardo-Ke** [comment]
resolved by java server side
