### ISSUE TITLE
JSON button not working

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#77]
@baimingze the jason button is not working properly. When I clicked the button nothing happen.

<img width="796" alt="screen shot 2016-06-15 at 18 05 19" src="https://cloud.githubusercontent.com/assets/52113/16089633/f9976a66-3323-11e6-8ef1-7ea66e235c02.png">

**Comment by ypriverol** [comment]
#69

**Comment by baimingze** [comment]
About the JSON button. We found it's hard to do the on-the-fly transfer from original JSON data to the downloadable JSON/XML/TAB files, because of the transfering is limited to ASCII charactors, rather than the Unicode ones.

One alternative way is doing the transfer in the backend system, who give an URL to the frontend system to download.

**Comment by ypriverol** [comment]
@baimingze feel free to add the methods in the web service. the XML and the JSON one

**Comment by baimingze** [comment]
done
