### ISSUE TITLE
Title not responsive

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#85]
<img width="933" alt="screen shot 2016-07-18 at 09 37 48" src="https://cloud.githubusercontent.com/assets/52113/16909708/319366ec-4ccc-11e6-99af-fa81fc841928.png">

**Comment by baimingze** [comment]
hi yasset, could rephrase this?
Things are fine in my local machine.

**Comment by ypriverol** [comment]
please see the image the banner is overlapping the home page search box.

**Comment by prvst** [comment]
Hi,
I just want to add a little bit more info about this issue that I also see here.

![screenshot at 2016-07-20 10 31 10](https://cloud.githubusercontent.com/assets/403705/16990341/b3972454-4e65-11e6-8cbb-7bf92f8f29c7.png)

As you can see, there are two issues here, the first one the the Title that looks to be unaware of the responsive adjustments. The second issue is the large gray area that makes the **Data set Information** header background. It seems that the area is also not readjusted.

I also checked the responsiveness of the main page and, as you can see below, there are some issues too. This is how the website looks on a Galaxy S5/ Iphone6 (375 x 667)

![screenshot at 2016-07-20 10 31 59](https://cloud.githubusercontent.com/assets/403705/16990472/1df1428a-4e66-11e6-9496-1f1238ec732b.png)

In overall, it seems some global settings are not working properly, and since mobile access dominate web today, I think it's imperative to fix those issues before moving on.

**Comment by abb44** [comment]
I try the web in multiple computers and it always look like this the home page. 

![screenshot from 2016-07-20 21 39 40](https://cloud.githubusercontent.com/assets/20402784/17002321/a267f99e-4ec2-11e6-8613-ccdad2cf7a1a.png)

**Comment by baimingze** [comment]
all done, except the last one. I will create an issue in ddi-web-service.
