### ISSUE TITLE
the Disqus URL of each dataset is wrong

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#98]
@baimingze if we click in the dataset title (see image), it goes to a wrong page. 

<img width="675" alt="screen shot 2016-07-21 at 09 55 02" src="https://cloud.githubusercontent.com/assets/52113/17017008/83d6bcba-4f29-11e6-825b-4a5d9e30aa8c.png">

This forward to this url http://www.omicsdi.org/dataset/massive/MSV000078942

Which is a wrong URL.

**Comment by baimingze** [comment]
It is a compromise we did with disqus.

disqus don't recoganize url with "#", e.g. "#/dataset/pride/pxd000001", but prefer "#!/dataset/pride/pxd000001".  

The thing is, omicsdi can not work well with "#!/dataset/pride/pxd000001".

so we give disqus an fake url without "#" to deal the issue, e.g. "/dataset/pride/pxd000001".

One possible solution for this issue is:
we write a javascript file as a 404 handler, let it redirect the wrong urls to the right one.

For example, we got http://www.omicsdi.org/dataset/massive/MSV000078942 in 404 handler, then redirect it to http://www.omicsdi.org/#/dataset/massive/MSV000078942. 

How do you think about this idea?

**Comment by ypriverol** [comment]
I really like the idea of redirecting when a use give an url wihout the # then we can redirect it to the proper url. then for me is a +1 for this solution.

**Comment by baimingze** [comment]
done
